// map_screen.h

// ditribution Global_MapScreen_Definitions {
#define MAPWIDTH     2
#define MAPHEIGHT    1
#define MAPLENGTH    MAPWIDTH * MAPHEIGHT
#define TILEWIDTH    2
#define TILEHEIGHT   2
#define TILELENGTH   TILEWIDTH * TILEHEIGHT
#define SCNTLEWIDTH  2
#define SCNTLEHEIGHT 1
#define SCNTLELENGTH SCNTLEWIDTH * SCNTLEHEIGHT
#define SCREENWIDTH  TILEWIDTH   * SCNTLEWIDTH
#define SCREENHEIGHT TILEHEIGHT  * SCNTLEHEIGHT
#define SCREENLENGTH SCREENWIDTH * SCREENHEIGHT