// map_const.h

// ditribution Global_Utility_Definitions {
#define MAPWIDTH     32
#define MAPHEIGHT    32
#define MAPLENGTH    MAPWIDTH * MAPHEIGHT
#define TILEWIDTH    8
#define TILEHEIGHT   4
#define TILELENGTH   TILEWIDTH * TILEHEIGHT
#define SCNTLEWIDTH  6
#define SCNTLEHEIGHT 6
#define SCNTLELENGTH SCNTLEWIDTH * SCNTLEHEIGHT
#define SCREENWIDTH  TILEWIDTH   * SCNTLEWIDTH
#define SCREENHEIGHT TILEHEIGHT  * SCNTLEHEIGHT
#define SCREENLENGTH SCREENWIDTH * SCREENHEIGHT